FROM php:7.4-apache
RUN apt-get update
RUN apt-get install -ym wget g++ curl git gnupg2 apt-utils software-properties-common libpng-dev

RUN docker-php-source extract \
    && docker-php-ext-install gd mysqli pdo_mysql \
    && docker-php-source delete

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN alias composer="php -n /usr/local/bin/composer"

WORKDIR /var/www/html

COPY sistema.conf /etc/apache2/sites-available/sistema.conf

RUN a2enmod rewrite
RUN a2ensite sistema.conf
RUN a2dissite 000-default
RUN service apache2 restart

EXPOSE 80

CMD ["apache2-foreground"]